# ---- BUILD ----

[tasks.build]
description = "Build client, generator and server"
clear = true
workspace = false
dependencies = ["build_server", "build_client"]

[tasks.build_release]
extend = "build"
description = "Build generator and server in release mode"
dependencies = ["build_server_release","build_client_release"]

[tasks.build_client]
description = "Build client"
workspace = false
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "client", "--target", "web", "--out-name", "package", "--dev"]

[tasks.build_client_release]
extend = "build_client"
description = "Build client in release mode"
args = ["build", "client", "--target", "web", "--out-name", "package", "--release"]

[tasks.build_generate]
description = "Build timetables generator"
workspace = false
command = "cargo"
args = ["build", "--package", "generator"]

[tasks.build_generate_release]
description = "Build timetables generator in release mode"
workspace = false
command = "cargo"
args = ["build", "--package", "generator", "--release"]

[tasks.build_server]
description = "Build server"
workspace = false
command = "cargo"
args = ["build", "--package", "ulak"]

[tasks.build_server_release]
extend = "build_server"
description = "Build server in release mode"
args = ["build", "--package", "ulak", "--release"]

# ---- START ----

[tasks.start]
description = "Build and start Tide server with client on port 8080"
workspace = false
command = "cargo"
args = ["run", "--package", "ulak", "client"]
dependencies = ["build"]

[tasks.start_release]
extend = "start"
description = "Build and start Actix server with client on port 8000 in release mode"
args = ["run", "--package", "ulak","--release", "client", "--release", "shared", "--release"]
dependencies = ["build_server_release", "build_client_release"]

# ---- LINT ----

[tasks.fmt]
description = "Format with rustfmt"
workspace = false
install_crate = { crate_name = "rustfmt-nightly", rustup_component_name = "rustfmt", binary = "rustfmt", test_arg = "--help" }
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt_check]
extend = "fmt"
description = "Check format with rustfmt"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
description = "Lint with Clippy"
clear = true
workspace = false
install_crate = { rustup_component_name = "clippy", binary = "cargo-clippy", test_arg = "--help" }
command = "cargo"
args = ["clippy", "--all-features", "--", "--deny", "clippy::all", "--deny", "clippy::pedantic", "--deny", "clippy::nursery"]
